AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'sepc/fixtures/**/*'
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: False
Metrics/MethodLength:
  Enabled: False
Metrics/ModuleLength:
  Enabled: False