sudo: false
language: ruby
bundler_args: --without system_tests development
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script: 
  - bundle exec rake validate
  - bundle exec rake lint
  - bundle exec rake spec
matrix:
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.2.6
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.3.3
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0"
notifications:
  email: false